# Necessary to get the logbook from Home Assistant!!!
# generate token under: http://homeassistant.local:8123/profile
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIwYTY5ZjNkNmQwYmU0NjU0OGM0OGIyNmM0NmMzYWU3YyIsImlhdCI6MTY5MzQyNDMxOCwiZXhwIjoyMDA4Nzg0MzE4fQ.jRgELnfVh2v3SEtU3SXC_5489X0jiAHLCZJHK3W_2gw
