# Necessary to get the logbook from Home Assistant!!!
# generate token under: http://homeassistant.local:8123/profile
token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkMmY5MDNmZGNjN2Q0MTk0Yjc0ZTczZGRkYzQ5Y2I4YSIsImlhdCI6MTY4MDczMTgwMywiZXhwIjoxOTk2MDkxODAzfQ.EKqFm9Ished-nuDhWWAX-yk4BW1_z1mBudFbUxUxSOc"
